# Generated by Django 5.2.17 on 2026-08-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asset_asset_tag_asset_make_asset_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
