# Generated by Django 5.2.17 on 2026-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asset_notes_asset_purchase_date_asset_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
