# Generated by Django 5.2.17 on 2026-08-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_due_date_ticketcomment_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
