# Generated by Django 5.2.17 on 2026-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='is_staged',
            field=models.BooleanField(default=False),
        ),
    ]
