# Generated by Django 5.2.17 on 2026-08-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_repair_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_slot', models.IntegerField()),
                ('u_size', models.IntegerField(default=1)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rack_assignment', to='core.networkdevice')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_assignments', to='core.location')),
            ],
        ),
    ]
