# Generated by Django 5.2.17 on 2026-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ticket_is_anonymous_ticket_location_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(blank=True, default='GENERIC', max_length=50),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='latency_ms',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='monitoring_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='open_ports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='os_fingerprint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_sys_descr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
