# Generated by Django 5.2.17 on 2026-08-18 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_networkdevice_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_u', models.PositiveIntegerField(default=40)),
                ('total_ports', models.PositiveIntegerField(default=24)),
                ('category', models.CharField(default='Cat6A', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField()),
                ('port_label', models.CharField(max_length=50)),
                ('port_type', models.CharField(choices=[('RJ45', 'RJ45 Copper'), ('SFP+', '10G SFP+'), ('FIBER_LC', 'Fiber LC'), ('QSFP', '40G/100G QSFP')], default='RJ45', max_length=20)),
                ('vlan_id', models.PositiveIntegerField(default=1)),
                ('speed_mbps', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('EMPTY', 'Empty'), ('FAULTY', 'Faulty')], default='EMPTY', max_length=20)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.networkdevice')),
                ('patch_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.patchpanel')),
            ],
            options={
                'ordering': ['port_number'],
            },
        ),
        migrations.CreateModel(
            name='CableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cable_type', models.CharField(choices=[('COPPER', 'Cat6A Copper'), ('FIBER_SINGLE', 'Single-Mode Fiber (OS2)'), ('FIBER_MULTI', 'Multi-Mode Fiber (OM4)'), ('DAC', 'Direct Attach Copper (DAC)')], default='COPPER', max_length=30)),
                ('color', models.CharField(choices=[('BLUE', 'Blue (LAN Data)'), ('YELLOW', 'Yellow (Single-Mode Fiber)'), ('ORANGE', 'Orange (Multi-Mode OM1/OM2)'), ('AQUA', 'Aqua (Multi-Mode OM3/OM4)'), ('PURPLE', 'Purple (Management/iDRAC)'), ('BLACK', 'Black (DAC / Uplink)'), ('RED', 'Red (Security / CCTV)')], default='BLUE', max_length=20)),
                ('length_meters', models.FloatField(default=2.0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('source_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_cables', to='core.port')),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_cables', to='core.port')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('total_u', models.PositiveIntegerField(default=42)),
                ('max_power_watts', models.PositiveIntegerField(default=5000)),
                ('max_weight_kg', models.FloatField(default=800.0)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired'), ('ACTIVE', 'Active')], db_index=True, default='ONLINE', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patchpanel',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_panels', to='core.rack'),
        ),
        migrations.CreateModel(
            name='RackMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_u', models.PositiveIntegerField()),
                ('u_height', models.PositiveIntegerField(default=1)),
                ('orientation', models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear')], default='FRONT', max_length=20)),
                ('power_draw_watts', models.PositiveIntegerField(default=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_mounts', to='core.asset')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_mounts', to='core.networkdevice')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='core.rack')),
            ],
            options={
                'ordering': ['-start_u'],
            },
        ),
    ]
