# Generated by Django 5.2.17 on 2026-08-19 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_patchpanel_port_cablelink_rack_patchpanel_rack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_id', models.CharField(max_length=50)),
                ('requester_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.TextField()),
                ('equipment_category', models.CharField(default='Laptop', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('CHECKED_OUT', 'Checked Out'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_APPROVAL', max_length=50)),
                ('technician_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to='core.employee')),
                ('specific_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
