# Generated by Django 5.2.17 on 2026-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_equipmentloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='is_rogue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='quarantined',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='vlan_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
