export enum Role {
  ADMIN = 'ADMIN',
  IT_SUPPORT = 'IT_SUPPORT',
  STOREKEEPER = 'STOREKEEPER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum HardwareCategory {
  LAPTOP = 'LAPTOP',
  DESKTOP = 'DESKTOP',
  MONITOR = 'MONITOR',
  PERIPHERAL = 'PERIPHERAL',
  NETWORKING = 'NETWORKING',
  SERVER = 'SERVER',
  MOBILE = 'MOBILE',
  PRINTING = 'PRINTING',
  POWER = 'POWER',
  CCTV = 'CCTV',
  COMMUNICATION = 'COMMUNICATION',
  TOOL = 'TOOL',
  CAMERA = 'CAMERA',
  CONSUMABLE = 'CONSUMABLE',
}

export enum HardwareStatus {
  IN_STOCK = 'IN_STOCK',
  INSTALLED = 'INSTALLED',
  ASSIGNED = 'ASSIGNED',
  BORROWED = 'BORROWED',
  UNDER_REPAIR = 'UNDER_REPAIR',
  MAINTENANCE = 'MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum RepairStatus {
  QUEUED = 'QUEUED',
  WAITING_PARTS = 'WAITING_PARTS',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum TransactionType {
  INTAKE = 'INTAKE',
  INSTALL = 'INSTALL',
  ISSUE = 'ISSUE',
  RETURN = 'RETURN',
  CONSUME = 'CONSUME',
  TRANSFER = 'TRANSFER',
}
