#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const versionFilePath = path.join(rootDir, 'VERSION');
const packageJsonPath = path.join(rootDir, 'apps', 'web', 'package.json');
const tauriConfPath = path.join(rootDir, 'apps', 'web', 'src-tauri', 'tauri.conf.json');
const cargoTomlPath = path.join(rootDir, 'apps', 'web', 'src-tauri', 'Cargo.toml');
const pythonVersionPath = path.join(rootDir, 'apps', 'api', 'core', 'version.py');

function getGitCommit() {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: rootDir, encoding: 'utf8' }).trim();
  } catch {
    return 'unknown_commit';
  }
}

function parseSemver(v) {
  const parts = v.trim().replace(/^v/, '').split('.').map(Number);
  if (parts.length !== 3 || parts.some(isNaN)) {
    throw new Error(`Invalid semver: "${v}"`);
  }
  return { major: parts[0], minor: parts[1], patch: parts[2] };
}

function bump(currentVersion, bumpType) {
  const parsed = parseSemver(currentVersion);
  if (bumpType === 'major') {
    return `${parsed.major + 1}.0.0`;
  } else if (bumpType === 'minor') {
    return `${parsed.major}.${parsed.minor + 1}.0`;
  } else if (bumpType === 'patch') {
    return `${parsed.major}.${parsed.minor}.${parsed.patch + 1}`;
  } else if (/^\d+\.\d+\.\d+$/.test(bumpType)) {
    return bumpType;
  } else {
    throw new Error(`Unknown bump type or invalid version: "${bumpType}". Use patch, minor, major, or X.Y.Z`);
  }
}

function main() {
  const arg = process.argv[2] || 'patch';
  let currentVersion = '0.3.3';

  if (fs.existsSync(versionFilePath)) {
    currentVersion = fs.readFileSync(versionFilePath, 'utf8').trim();
  }

  const newVersion = bump(currentVersion, arg);
  const gitCommit = getGitCommit();
  const buildTimestamp = new Date().toISOString();

  console.log(`Bumping version: ${currentVersion} -> ${newVersion} (${arg})`);

  // 1. Update root VERSION
  fs.writeFileSync(versionFilePath, `${newVersion}\n`, 'utf8');

  // 2. Update apps/web/package.json
  if (fs.existsSync(packageJsonPath)) {
    const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    pkg.version = newVersion;
    fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
  }

  // 3. Update apps/web/src-tauri/tauri.conf.json
  if (fs.existsSync(tauriConfPath)) {
    const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
    tauriConf.version = newVersion;
    if (tauriConf.app && Array.isArray(tauriConf.app.windows)) {
      tauriConf.app.windows.forEach((w) => {
        w.title = `Pulse IT Operations v${newVersion}`;
      });
    }
    fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2) + '\n', 'utf8');
  }

  // 4. Update apps/web/src-tauri/Cargo.toml
  if (fs.existsSync(cargoTomlPath)) {
    let cargo = fs.readFileSync(cargoTomlPath, 'utf8');
    cargo = cargo.replace(/version\s*=\s*"[^"]+"/, `version = "${newVersion}"`);
    fs.writeFileSync(cargoTomlPath, cargo, 'utf8');
  }

  // 5. Update apps/api/core/version.py
  const pyContent = `# Auto-generated by scripts/bump_version.js
APP_VERSION = "${newVersion}"
GIT_COMMIT = "${gitCommit}"
BUILD_TIMESTAMP = "${buildTimestamp}"
ENVIRONMENT = "production"
`;
  fs.writeFileSync(pythonVersionPath, pyContent, 'utf8');

  console.log(`SUCCESS: Unified version synchronized to v${newVersion} across all components.`);
}

main();
